name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Build with maven
      run: ls
      run: pwd 
      run: cd ..
      run: ls 
      run: mvn -B package --file ../pom.xml
